//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Calificaciones
    {
        public int Id_Calificacion { get; set; }
        public int Id_Actividad { get; set; }
        public int No_Control { get; set; }
        public string Retroalimentacion { get; set; }
    }
}
