//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public int Id_Usuario { get; set; }
        public string Nom_Docente { get; set; }
        public string Contraseña { get; set; }
        public string Correo { get; set; }
        public int Id_Perfil { get; set; }
    }
}
