//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Indicadores
    {
        public int Id_Indicadores { get; set; }
        public string Nom_Indicador { get; set; }
        public string Sigla { get; set; }
        public string Descripcion { get; set; }
    }
}
