//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Materias
    {
        public int Id_Materia { get; set; }
        public string Nom_Materia { get; set; }
        public string Clave { get; set; }
        public int Id_Carrera { get; set; }
    }
}
