//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Temas
    {
        public int Id_Tema { get; set; }
        public string Nom_Tema { get; set; }
        public string Posicion { get; set; }
        public int Id_Grupo { get; set; }
        public string Competencia { get; set; }
    }
}
