//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Actividades
    {
        public int Id_Actividad { get; set; }
        public int Id_Tema { get; set; }
        public int Valor { get; set; }
        public string Nombre { get; set; }
        public int Id_Instrumento { get; set; }
    }
}
