//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Grupo_Alumno
    {
        public int Id_Grupo_Alumno { get; set; }
        public int Clave_Grupo { get; set; }
        public int No_Control { get; set; }
    }
}
